name: maple
description: Maple Media App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  firebase_storage: ^11.0.8
  cloud_firestore: ^4.1.0
  google_sign_in: ^5.4.2
  provider: ^6.0.4
  flutter_html: ^2.2.1
  youtube_player_flutter: ^8.1.1
  esys_flutter_share_plus: ^2.2.0
  flutter_share: ^2.0.0
  image_picker: ^0.8.6
  rating_dialog: ^2.0.4
  webview_flutter: ^2.0.4
  another_flushbar:
  glutton:
  url_launcher: ^6.1.7
  image_cropper: ^3.0.1
  pod_player: ^0.1.0
  icons_launcher: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

icons_launcher:
  image_path: "assets/images/maple-app-icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/Bebas-Neue/BebasNeueBook.ttf
        - asset: assets/fonts/Bebas-Neue/BebasNeueBold.ttf
          weight: 700
    
    - family: Sequel
      fonts:
        - asset: assets/fonts/Sequel-Sans/ttf/Sequel-Sans-Black-Body.ttf
        - asset: assets/fonts/Sequel-Sans/ttf/Sequel-Sans-Book-Body.ttf
          weight: 100
        - asset: assets/fonts/Sequel-Sans/ttf/Sequel-Sans-Bold-Body.ttf
          weight: 700